on:
  push:

jobs:
  typhon:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@e4ed13ca426fa34c864a6cf26125e3cd9c68d700
      - run: nix --version
      - uses: typhon-ci/typhon-gh-action@main
        with:
          secrets: ${{ secrets.TYPHON_SECRETS }}
