on:
  push:

jobs:
  typhon:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix --version
      - uses: typhon-ci/typhon-gh-action@main
        with:
          secrets: ${{ secrets.TYPHON_SECRETS }}
