on:
  push:

jobs:
  typhon:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: typhon-ci/typhon-github-action@pnm/age
        with:
          key: ${{ secrets.TYPHON_KEY }}
